repos:
  - title: Bénédicte Lambert
    description: Mes recettes
    href: https://bndct-lmbrt.github.io/mes-recettes/

  - title: Armel Lecoz
    description: Démocratie ouverte
    href: http://pointbar.github.io/democratie_ouverte/

  - title: Julia Barbelane
    description: Réflexions
    href: https://julia-barbelane.github.io/reflexions/

  - title: Lilian Ricaud
    description: Travail en réseau
    href: http://pointbar.github.io/travail-en-reseau/
